name: Python 3.9 Linux Setup

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # Use Linux runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Cache Python packages to speed up future runs
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: pip_packages
        key: python-packages-${{ runner.os }}-${{ hashFiles('requirements_pylinux.txt') }}
        restore-keys: |
          python-packages-${{ runner.os }}-

    # Step 4: Download Python dependencies as `.whl` or `.tar.gz`
    - name: Download Python dependencies
      run: |
        mkdir -p pip_packages
        pip download --dest pip_packages -r requirements_pylinux.txt

    # Step 5: Install Python dependencies from cached/downloaded files
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --no-index --find-links=pip_packages -r requirements_pylinux.txt

    # Step 6: Debugging step: Check downloaded `.whl` and `.tar.gz` files
    - name: List downloaded Python packages
      run: ls -lh pip_packages/

    # Step 7: Upload downloaded Python packages as an artifact
    - name: Upload Python package library
      uses: actions/upload-artifact@v4
      with:
        name: python-packages-linux
        path: pip_packages/
