name: Python Windows Setup

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest  # This will use a Windows runner for your workflow

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Create virtual environment
    - name: Create virtual environment
      run: |
        if (Test-Path venv) {
          Remove-Item -Recurse -Force venv
        }
        python -m venv venv
        .\venv\Scripts\activate

    # Step 4: Debug - List directory structure
    - name: List directory structure
      run: Get-ChildItem -Recurse

    # Step 5: Download dependencies instead of installing them
    - name: Download Python packages
      run: |
        .\venv\Scripts\activate
        mkdir wheelhouse
        pip download -r requirements_py.txt --dest=wheelhouse

    # Step 6: Upload downloaded packages as an artifact
    - name: Upload wheelhouse
      uses: actions/upload-artifact@v4
      with:
        name: python-packages
        path: wheelhouse/
